### ISSUE TITLE
Packaged Mac application contains a line that stops it from working

### ISSUE THREAD

**Issue by AdamCarroll** [VocabHunter/VocabHunter#1]
The Apple Mac version of the system built with the Oracle JavaFX Self-Contained Application Packaging tool doesn't work.  There is a workaround in the Gradle script to fix the problem but as it stands it prevents a clean build of a DMG package.  See the following StackOverflow question for details: http://stackoverflow.com/q/33898461

**Comment by FibreFoX** [comment]
As stated on StackOverflow:
This bug starts to exist from Oracle Java 1.8.0 Update 60, I already reported this but it's not a official bug yet.

The problem is the internal packager using INI-file-format now, you can see [my findings here](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/167).

You should be able to set the bundle-argument "launcher-cfg-format" with the value "prop" ([like here](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/ea272f3b03f9ff8d457992fc12ccae156194849e/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L428)), this should do the trick:
```
            <fx:bundleArgument arg="launcher-cfg-format" value="prop"/>
```

**Disclaimer: I'm the maintainer of the javafx-maven-plugin**

**Comment by AdamCarroll** [comment]
With your help @FibreFoX this is fixed.  Thanks very much!
