### ISSUE TITLE
Open .properties file shows the content in one sentence not in xy sentence

### ISSUE THREAD

**Issue by Naoghuman** [VocabHunter/VocabHunter#15]
Hi Adam,

I downloaded the zip VocabHunter-1.0.15 and tried to create a `New` session with the option `All Files (*.*)` to load a `xy.properties` file.

Loading can be done, but I see that the engine doesn't split the content from the `.properties` file into xy sentence. So I see in the application when I selected a word a really long sentence.

So I think if
a) A `.properties` file isn't supported, then a dialog should shows this information,
b) if a `.properties` file is okay, then the parser? should split the content from the file (lines) into sentences.

Greetings
Peter

**Comment by AdamCarroll** [comment]
Hi Peter,

VocabHunter uses Apache Tika to read all sorts of different text file formats.  I think that in this case the properties file is not a specific format handled by Apache Tika and so is just being treated as a plain text file.  VocabHunter then runs the analysis and looks for sentences on the complete text file, without treating the keys and values specially.

My main aim at the moment is to get this working for novels and articles (documents with a basic sentence structure) so that language learners can learn the vocab.  Did you have a particular need to read properties files or were you just testing out the system?  Either way, I appreciate your feedback!

Cheers, Adam.

**Comment by Naoghuman** [comment]
No particular need to read properties file - just playing a little with the app.

When you want that the user can only create sessions with .xy files then a possible solutions is like how in #14 . Remove the `All File (*.*)` option. So the user is forced to used a specific file format.

**Comment by AdamCarroll** [comment]
It's great to have someone else trying out the app and giving feedback as it can really help to catch the things that I miss, just like the problem with the all file option in #14.

In this case I'm inclined to leave the All Files option even though it will cause problems in cases like the one that you have identified.  Apache Tika offers a fantastically wide set of support for formats and I don't think I'll list them all out in the dialogue.  The All Files option helps to encourage the user to try out file formats to see if they can get some success with them.  Even partial success may be useful to a language learner as even if they don't get a perfect result, they may still get a useful set of words.

Thanks again for the feedback!
